# Generated by Django 4.2.5 on 2023-10-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('house_number', models.CharField(max_length=150, verbose_name='House Number')),
                ('product_name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('product_model', models.CharField(max_length=150, verbose_name='Product Model')),
                ('product_date', models.DateField(verbose_name='Product Date')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Debt')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('supplier', models.ForeignKey(blank=True, default='null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.chainelement', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Chain Element',
                'verbose_name_plural': 'Chain Elements',
                'ordering': ['supplier', 'name'],
            },
        ),
    ]
