# Generated by Django 4.2.5 on 2023-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainelement',
            name='chain_level',
            field=models.IntegerField(choices=[(0, 'Factory'), (1, 'Retail'), (2, 'Entrepreneur')], verbose_name='Chain Level'),
        ),
    ]
