# Generated by Django 4.2.5 on 2023-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainelement',
            name='city',
            field=models.CharField(default='Not indicated', max_length=150, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='chainelement',
            name='country',
            field=models.CharField(default='Not indicated', max_length=150, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='chainelement',
            name='house_number',
            field=models.CharField(default='Not indicated', max_length=150, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='chainelement',
            name='street',
            field=models.CharField(default='Not indicated', max_length=150, verbose_name='Street'),
        ),
    ]
