# Generated by Django 4.2.5 on 2023-10-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_chainelement_city_alter_chainelement_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainelement',
            name='supplier',
            field=models.ForeignKey(choices=[('factory', 'factory'), ('retail', 'retail'), ('entrepreneur', 'entrepreneur')], default='No Supplier', on_delete=django.db.models.deletion.SET_DEFAULT, to='suppliers.chainelement', verbose_name='Supplier'),
        ),
    ]
