# Generated by Django 4.2.5 on 2023-10-09 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_chainelement_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainelement',
            name='supplier',
            field=models.ForeignKey(choices=[('No Supplier', 'No Supplier'), ('Factory', 'Factory'), ('Retail', 'Retail'), ('Entrepreneur', 'Entrepreneur')], default='No Supplier', on_delete=django.db.models.deletion.SET_DEFAULT, to='suppliers.chainelement', verbose_name='Supplier'),
        ),
    ]
