# Generated by Django 4.2.5 on 2023-10-09 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_alter_chainelement_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainelement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.chainelement', verbose_name='Supplier'),
        ),
    ]
